using System;

namespace codecrafters_redis.src.Services;

public record StreamId(long Milliseconds, int Sequence)
{
    private const string MinId = "0-0";
    private const string AutoSymbol = "*";

    public static bool TryParse(string id)
    {
        var parts = id.Split('-');
        return parts.Length == 2 &&
               long.TryParse(parts[0], out var ms) &&
               int.TryParse(parts[1], out var seq) &&
               ms >= 0 && seq >= 0;
    }

    public static StreamId Parse(string id)
    {
        var parts = id.Split('-');
        if (parts.Length != 2 ||
            !long.TryParse(parts[0], out var ms) ||
            !int.TryParse(parts[1], out var seq))
        {
            System.Console.WriteLine($"Invalid ID format: {id}");
            throw new ArgumentException("Invalid ID format");
        }
        return new StreamId(ms, seq);
    }

    public static bool IsFullyAutoGenerated(string id) =>
        id == AutoSymbol;

    public static bool IsAutoSequence(string id) =>
        id.Split('-') is var parts && parts.Length == 2 && parts[1] == AutoSymbol;

    public static bool IsMinimumId(string id) => id == MinId;

    public static bool operator <(StreamId left, StreamId right) =>
        left.Milliseconds < right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence < right.Sequence);

    public static bool operator >(StreamId left, StreamId right) =>
        left.Milliseconds > right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence > right.Sequence);

    public static bool operator <=(StreamId left, StreamId right) =>
        left.Milliseconds < right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence <= right.Sequence);

    public static bool operator >=(StreamId left, StreamId right) =>
        left.Milliseconds > right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence >= right.Sequence);
    public override string ToString() => $"{Milliseconds}-{Sequence}";
}

public class Stream
{
    public required StreamId Id { get; set; }
    public required Dictionary<string, string> Fields { get; set; }
}

public class StreamStorageService
{
    private readonly Dictionary<string, List<Stream>> _streams = new();

    public Task<string> AddEntryAsync(string key, string id, Dictionary<string, string> fields)
    {
        // Validate minimum ID
        if (StreamId.IsMinimumId(id))
        {
            throw new ArgumentException("The ID specified in XADD must be greater than 0-0");
        }

        EnsureStreamExists(key);

        // Resolve ID (handle auto-sequence)
        StreamId finalId;
        if (StreamId.IsFullyAutoGenerated(id))
        {
            finalId = new StreamId(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(), 0);
        }
        else if (StreamId.IsAutoSequence(id))
        {
            var parts = id.Split('-');
            var milliseconds = long.Parse(parts[0]);

            finalId = milliseconds == 0
                ? new StreamId(0, 1)
                : GenerateNextSequence(milliseconds, _streams[key]);
        }
        else
        {
            finalId = StreamId.Parse(id);
        }

        return AddEntryAsync(key, finalId, fields);
    }

    public Task<string> AddEntryAsync(string key, StreamId id, Dictionary<string, string> fields)
    {
        EnsureStreamExists(key);
        ValidateIdIsGreaterThanLast(id, _streams[key]);

        var entry = new Stream { Id = id, Fields = fields };
        _streams[key].Add(entry);

        return Task.FromResult(id.ToString());
    }

    private void EnsureStreamExists(string key)
    {
        _streams.TryAdd(key, new List<Stream>());
    }

    private static StreamId GenerateNextSequence(long milliseconds, List<Stream> streams)
    {
        var sequence = streams
            .Where(s => s.Id.Milliseconds == milliseconds)
            .Select(s => s.Id.Sequence)
            .DefaultIfEmpty(-1)
            .Max() + 1;

        return new StreamId(milliseconds, sequence);
    }

    private static void ValidateIdIsGreaterThanLast(StreamId id, List<Stream> streams)
    {
        if (streams.Count == 0) return;

        var lastId = streams.Last().Id;

        if (!(id > lastId))
        {
            var errorMessage = lastId.ToString() == "0-0"
                ? $"must be greater than {lastId}"
                : "is equal or smaller than the target stream top item";

            throw new ArgumentException($"The ID specified in XADD {errorMessage}");
        }
    }

    public Task<string> AddEntryAsync(string key, Dictionary<string, string> fields)
    {
        var id = new StreamId(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(), 0);
        return AddEntryAsync(key, id, fields);
    }

    public Task<StreamId> ResolveAutoSequenceId(string key, long milliseconds)
    {
        EnsureStreamExists(key);
        var result = GenerateNextSequence(milliseconds, _streams[key]);
        return Task.FromResult(result);
    }

    public Task<List<Stream>?> GetEntriesAsync(string key)
    {
        if (_streams.TryGetValue(key, out var entries))
        {
            return Task.FromResult<List<Stream>?>(entries);
        }
        return Task.FromResult<List<Stream>?>(null);
    }

    public async Task<List<Stream>?> GetRangeAsync(string key, string id)
    {
        EnsureStreamExists(key);
        if (id == "-")
        {
            return _streams[key];
        }
        if (id == "+")
        {
            return new List<Stream>();
        }
        if (id.Split('-').Length < 2)
        {
            id = $"{id}-0";
        }
        var startId = StreamId.Parse(id);
        var result = _streams[key]
            .Where(s => s.Id > startId)
            .ToList();

        return await Task.FromResult(result);
    }

    public async Task<List<Stream>?> GetRangeAsync(string key, string start, string end)
    {
        EnsureStreamExists(key);
        List<Stream>? result;
        if (start == "-")
        {
            result = _streams[key]
                .Where(s => s.Id <= StreamId.Parse(end))
                .ToList();
            return result;
        }
        if (end == "+")
        {
            result = _streams[key]
                .Where(s => s.Id >= StreamId.Parse(start))
                .ToList();
            return result;
        }
        if (start.Split('-').Length < 2)
        {
            start = $"{start}-0";
        }

        if (end.Split('-').Length < 2)
        {
            var lastId = _streams[key].Where(id => id.Id.Milliseconds == long.Parse(end)).Last().Id;
            end = $"{end}-{lastId.Sequence}";
        }

        var startId = StreamId.Parse(start);
        var endId = StreamId.Parse(end);

        result = _streams[key]
            .Where(s => s.Id >= startId && s.Id <= endId)
            .ToList();

        return await Task.FromResult(result);
    }
}
