using System;
using System.Collections.Concurrent;
using codecrafters_redis.src.Infrastructure;
using codecrafters_redis.src.Models;
using Stream = codecrafters_redis.src.Models.Stream;

namespace codecrafters_redis.src.Services;

public class StreamStorageService
{
    private readonly ConcurrentDictionary<string, BlockingStreamList> _streams = new();

    public Task<string> AddEntryAsync(string key, string id, Dictionary<string, string> fields)
    {
        
        if (StreamId.IsMinimumId(id))
        {
            throw new ArgumentException("The ID specified in XADD must be greater than 0-0");
        }

        EnsureStreamExists(key);

        
        StreamId finalId;
        if (StreamId.IsFullyAutoGenerated(id))
        {
            finalId = new StreamId(DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(), 0);
        }
        else if (StreamId.IsAutoSequence(id))
        {
            var parts = id.Split('-');
            var milliseconds = long.Parse(parts[0]);

            finalId = milliseconds == 0
                ? new StreamId(0, 1)
                : GenerateNextSequence(milliseconds, _streams[key]);
        }
        else
        {
            finalId = StreamId.Parse(id);
        }

        return AddEntryAsync(key, finalId, fields);
    }

    public async Task<string> AddEntryAsync(string key, StreamId id, Dictionary<string, string> fields)
    {
        EnsureStreamExists(key);
        ValidateIdIsGreaterThanLast(id, _streams[key]);

        var entry = new Stream { Id = id, Fields = fields };
        await _streams[key].AddAsync(entry);

        return id.ToString();
    }

    private void EnsureStreamExists(string key)
    {
        _streams.TryAdd(key, new BlockingStreamList());
    }

    private static StreamId GenerateNextSequence(long milliseconds, BlockingStreamList streams)
    {
        var sequence = streams.items
            .Where(s => s.Id.Milliseconds == milliseconds)
            .Select(s => s.Id.Sequence)
            .DefaultIfEmpty(-1)
            .Max() + 1;

        return new StreamId(milliseconds, sequence);
    }

    private static void ValidateIdIsGreaterThanLast(StreamId id, BlockingStreamList streams)
    {
        if (streams.items.Count == 0) return;

        var lastId = streams.items.Last().Id;

        if (!(id > lastId))
        {
            var errorMessage = lastId.ToString() == "0-0"
                ? $"must be greater than {lastId}"
                : "is equal or smaller than the target stream top item";

            throw new ArgumentException($"The ID specified in XADD {errorMessage}");
        }
    }


    public Task<BlockingStreamList?> GetEntriesAsync(string key)
    {
        if (_streams.TryGetValue(key, out var entries))
        {
            return Task.FromResult<BlockingStreamList?>(entries);
        }
        return Task.FromResult<BlockingStreamList?>(null);
    }

    public async Task<List<Stream>?> GetRangeAsync(string key, int timeoutMilliseconds)
    {
        EnsureStreamExists(key);
        var result = await _streams[key].GetStreamsAsync(timeoutMilliseconds);

        return await Task.FromResult(result);
        
    }

    public async Task<List<Stream>?> GetRangeAsync(string key, string id, int timeoutMilliseconds)
    {
        EnsureStreamExists(key);
        if (id == "-")
        {
            return _streams[key].items;
        }
        if (id == "+")
        {
            return new List<Stream>();
        }
        if (id.Split('-').Length < 2)
        {
            id = $"{id}-0";
        }
        var startId = StreamId.Parse(id);
        var result = await _streams[key].GetStreamsAsync(startId, timeoutMilliseconds);

        return await Task.FromResult(result);
    }

    public async Task<List<Stream>?> GetRangeAsync(string key, string id)
    {
        EnsureStreamExists(key);
        if (id == "-")
        {
            return _streams[key].items;
        }
        if (id == "+")
        {
            return new List<Stream>();
        }
        if (id.Split('-').Length < 2)
        {
            id = $"{id}-0";
        }
        var startId = StreamId.Parse(id);
        var result = _streams[key].items
            .Where(s => s.Id > startId)
            .ToList();

        return await Task.FromResult(result);
    }

    public async Task<List<Stream>?> GetRangeAsync(string key, string start, string end)
    {
        EnsureStreamExists(key);
        List<Stream>? result;
        if (start == "-")
        {
            result = _streams[key].items
                .Where(s => s.Id <= StreamId.Parse(end))
                .ToList();
            return result;
        }
        if (end == "+")
        {
            result = _streams[key].items
                .Where(s => s.Id >= StreamId.Parse(start))
                .ToList();
            return result;
        }
        if (start.Split('-').Length < 2)
        {
            start = $"{start}-0";
        }

        if (end.Split('-').Length < 2)
        {
            var lastId = _streams[key].items.Where(id => id.Id.Milliseconds == long.Parse(end)).Last().Id;
            end = $"{end}-{lastId.Sequence}";
        }

        var startId = StreamId.Parse(start);
        var endId = StreamId.Parse(end);

        result = _streams[key].items
            .Where(s => s.Id >= startId && s.Id <= endId)
            .ToList();

        return await Task.FromResult(result);
    }
}
