namespace codecrafters_redis.src.Models;

public record StreamId(long Milliseconds, int Sequence)
{
    private const string MinId = "0-0";
    private const string AutoSymbol = "*";

    public static bool TryParse(string id)
    {
        var parts = id.Split('-');
        return parts.Length == 2 &&
               long.TryParse(parts[0], out var ms) &&
               int.TryParse(parts[1], out var seq) &&
               ms >= 0 && seq >= 0;
    }

    public static StreamId Parse(string id)
    {
        var parts = id.Split('-');
        if (parts.Length != 2 ||
            !long.TryParse(parts[0], out var ms) ||
            !int.TryParse(parts[1], out var seq))
        {
            System.Console.WriteLine($"Invalid ID format: {id}");
            throw new ArgumentException("Invalid ID format");
        }
        return new StreamId(ms, seq);
    }

    public static bool IsFullyAutoGenerated(string id) =>
        id == AutoSymbol;

    public static bool IsAutoSequence(string id) =>
        id.Split('-') is var parts && parts.Length == 2 && parts[1] == AutoSymbol;

    public static bool IsMinimumId(string id) => id == MinId;

    public static bool operator <(StreamId left, StreamId right) =>
        left.Milliseconds < right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence < right.Sequence);

    public static bool operator >(StreamId left, StreamId right) =>
        left.Milliseconds > right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence > right.Sequence);

    public static bool operator <=(StreamId left, StreamId right) =>
        left.Milliseconds < right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence <= right.Sequence);

    public static bool operator >=(StreamId left, StreamId right) =>
        left.Milliseconds > right.Milliseconds ||
        (left.Milliseconds == right.Milliseconds && left.Sequence >= right.Sequence);
    public override string ToString() => $"{Milliseconds}-{Sequence}";
}
